### Additional setup for zbase dev
ARG COMPOSER_VERSION=2.9.2 # https://hub.docker.com/_/composer/tags
ARG VSCODE_VERSION=1.107.1 # https://github.com/microsoft/vscode/releases

FROM composer:${COMPOSER_VERSION} AS composer

FROM ghcr.io/zetaoss/zbase:latest

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN set -eux \
    && curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sh \
    && apt-get update && apt-get install -y --no-install-recommends \
        inotify-tools \
        jq \
        mariadb-client \
        procps \
        psmisc \
        redis-tools \
        supervisor \
        tini \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get update \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && rm -rf /tmp/pear/

RUN set -eux \
    && VSCODE_SERVER_DIR=/root/.vscode-server \
    && SHA="$(curl -s https://api.github.com/repos/microsoft/vscode/git/ref/tags/${VSCODE_VERSION} | jq -r '.object.sha')" \
    && mkdir -p "${VSCODE_SERVER_DIR}/bin/${SHA}" \
    && curl -L "https://update.code.visualstudio.com/commit:${SHA}/server-linux-x64/stable" -o vscode-server.tar.gz \
    && tar -xz -C "${VSCODE_SERVER_DIR}/bin/${SHA}" --strip-components=1 -f vscode-server.tar.gz \
    && rm -f vscode-server.tar.gz \
    && for extension in \
        bradlc.vscode-tailwindcss \
        dbaeumer.vscode-eslint \
        editorconfig.editorconfig \
        evgenius33.laravel-pint-fixer \
        laravel.vscode-laravel \
        ms-vscode.makefile-tools \
        shufo.vscode-blade-formatter \
        vitest.explorer \
        vue.volar; do \
        "${VSCODE_SERVER_DIR}/bin/${SHA}/bin/code-server" --install-extension "${extension}"; \
    done

RUN set -eux \
    && cd / \
    && git clone https://github.com/zetaoss/zengine.git app \
    && cd /app/ \
    && cp -a  /var/www/html                     /app/w \
    && cp -a  /app/w/composer.local.json-sample /app/w/composer.local.json \
    && ln -rs /app/mwz/extensions/ZetaExtension /app/w/extensions/ \
    && ln -rs /app/mwz/skins/ZetaSkin           /app/w/skins/ \
    && cd /app/laravel/              && composer install --no-interaction --prefer-dist \
    && cd /app/w/                    && composer update  --no-interaction --prefer-dist \
    && cd /app/vue/                  && pnpm install \
    && cd /app/w/skins/ZetaSkin/vue/ && pnpm install && pnpm run build \
    && chown www-data:www-data -R /app/*
