FROM ghcr.io/zetaoss/zbase:latest

COPY --from=composer:2.2.25 /usr/bin/composer /usr/bin/composer

RUN set -eux \
    && apt-get update && apt-get install -y \
    inotify-tools \
    procps \
    supervisor \
    tini \
    && rm -rf /var/lib/apt/lists/* \
    && pecl install \
    xdebug \
    && docker-php-ext-enable \
    xdebug \
    && rm -rf /tmp/pear/
