# https://github.com/wikimedia/mediawiki-docker
FROM ghcr.io/zetaoss/zbase:latest

RUN set -eux \
    && apk add --no-cache \
    composer \
    inotify-tools \
    linux-headers \
    nodejs \
    && docker-php-ext-install zip \
    && pecl install \
    xdebug \
    && docker-php-ext-enable \
    xdebug \
    && rm -rf /tmp/pear/
